name: l2v
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11.7
  - pytorch=2.2.0
  - pytorch-cuda=11.8
  - pytorch-lightning=2.1.3
  - pandas=2.1.1
  - dask=2023.11.0
  - matplotlib=3.8
  - h5py=3.9.0
  - pip:
      - performer-pytorch==1.1.4
